name: flutter_beacon
description: Flutter plugin for scanning beacon (iBeacon platform) devices on Android and iOS.
version: 0.2.4
homepage: https://github.com/alann-maulana/flutter_beacon

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.flutterbeacon
    pluginClass: FlutterBeaconPlugin
